---

- name: homebrew install dockutil package see https://github.com/kcrawford/dockutil
  homebrew:
    name: "{{ item.name | default(item) }}"
    install_options: "{{ item.install_options | default(omit) }}"
    state: present
    update_homebrew: yes
  loop:
    - dockutil

- name: Install dockutil directly in /usr/local/bin (workaround) [1/2]
  shell: curl --silent "https://api.github.com/repos/kcrawford/dockutil/releases/latest" | jq -r '.assets[].browser_download_url' | grep pkg
  register: dockutil_latest_pkg

- name: Install dockutil directly in /usr/local/bin (workaround) [1/2]
  shell: "{{ item }}"
  with_items:
    - curl -sL {{ dockutil_latest_pkg.stdout }} -o /tmp/dockutil.pkg
    - sudo installer -pkg "/tmp/dockutil.pkg" -target /
    - rm /tmp/dockutil.pkg

- name: Remove all crap from Dock
  shell: dockutil --remove '{{ item }}'
  ignore_errors: true
  loop: "{{ dockutil_remove  }}"

- name: Check if items in dock exist
  shell: dockutil --find '{{ item.name }}' || dockutil --add '{{ item.path }}'
  loop: "{{ dockutil_persist }}"

- name: Fix order
  shell: dockutil --move '{{ item.name }}' --position {{ item.pos }}
  loop: "{{ dockutil_persist }}"
