---

- name: Check if homebrew is Installed
  stat:
    path: "/usr/local/bin/brew"
  register: "homebrew_check"

- name: Install homebrew (using CURL)
  shell: '/usr/bin/ruby -e \
    "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"'
  when: not homebrew_check.stat.exists

- name: homebrew update itself and packages
  homebrew:
    update_homebrew: yes
    upgrade_all: yes
  when: homebrew_check.stat.exists

- name: homebrew add tap's
  homebrew_tap: "tap={{ item }} state=present"
  loop: "{{ brew_taps }}"

- name: homebrew install packages
  homebrew:
    name: "{{ item.name | default(item) }}"
    install_options: "{{ item.install_options | default(omit) }}"
    state: present
  loop: "{{ brew_packages }}"

- name: homebrew cask install packages
  homebrew_cask:
    name: "{{ item.name | default(item) }}"
    install_options: "{{ item.install_options | default(omit) }}"
    state: present
  loop: "{{ brew_cask_packages }}"
  tags:
    - travis-do-not
