---

- name: Check if vlc package is already installed
  shell: brew list --cask | grep vlc
  register: homebrew_vlc_installed
  failed_when: homebrew_vlc_installed.rc > 1

- name: homebrew cask install vlc packages
  homebrew:
    name: "{{ item.name | default(item) }}"
    install_options: "{{ item.install_options | default(omit) }}"
    state: present
  loop:
    - vlc
  when: '"vlc" not in homebrew_vlc_installed.stdout'

- name: Install vlc settings
  copy:
    src: "{{ role_path }}/files/"
    dest: "~/Library/Preferences/org.videolan.vlc/"
    force: no
