---

- name: Check if scansnap package is already installed
  shell: brew list --cask | grep fujitsu-scansnap-home
  register: homebrew_scansnap_installed
  failed_when: homebrew_scansnap_installed.rc > 1

- name: homebrew cask install scansnap packages
  homebrew:
    name: "{{ item.name | default(item) }}"
    install_options: "{{ item.install_options | default(omit) }}"
    state: present
  loop:
    - fujitsu-scansnap-home
  when: '"fujitsu-scansnap-home" not in homebrew_scansnap_installed.stdout'

- name: Stop running scansnap app
  command: osascript -e 'quit app "ScanSnap Home"'

# http://www.documentsnap.com/how-to-backup-your-scansnap-profile-settings-on-the-mac/
#
# ScanSnap Manager (for fujitsu-scansnap-manager-ix500) [OLD]:
# jp.co.pfu.ScanSnap.V10L10.plist
#
# ScanSnap Home (for fujitsu-scansnap-home):
# com.fujitsu.pfu.ScanSnapHome.plist
# com.fujitsu.pfu.ScanSnapHomeSetting.plist
- name: Install scansnap settings
  copy:
    src: "{{ role_path }}/files/"
    dest: "~/Library/Preferences/"
    force: yes
