---

- name: Setup dotfiles using Python bootstrap.py script
  import_tasks: dotfiles.yml

- name: Setup ssh config
  import_tasks: ssh.yml

# https://developer.hashicorp.com/terraform/cli/config/config-file
- name: Copy ~/.terraformrc from .terraformrc
  copy:
    src:  "{{ role_path }}/files/.terraformrc"
    dest: "~/.terraformrc"
