---

- name: Execute OSX hombrew installation for python
  import_tasks: osx-python-install.yaml
  when: ansible_os_family == 'Darwin'

- name: Copy pip config
  copy:
    src: "{{ role_path }}/files/"
    dest: "~"
    force: yes
