---
- name: Check if ~/.gitconfig exists
  stat:
    path: ~/.gitconfig
  register: gitconfig

- name: Create ~/.gitconfig
  template:
    src: gitconfig.j2
    dest: "~/.gitconfig"
  when: not gitconfig.stat.exists

- name: Set diff-so-fancy as default for git diff https://github.com/so-fancy/diff-so-fancy
  shell: "git config --global core.pager 'diff-so-fancy | less --tabs=4 -RFX'"

# https://stackoverflow.com/questions/2788092/start-a-git-commit-message-with-a-hashmark
# https://stackoverflow.com/questions/16164624/vim-syntax-highlighting-for-git-commit-messages-custom-commentchar
- name: Switch git comment char to $ instead of \#
  shell: "git config --global core.commentchar '$'"

# https://stackoverflow.com/questions/30542491/push-force-with-lease-by-default
- name: Enable force with lease as default for git push
  shell: "git config --global alias.pushf 'push --force-with-lease'"

# https://stackoverflow.com/questions/6089294/why-do-i-need-to-do-set-upstream-all-the-time
# https://stackoverflow.com/questions/23918062/simple-vs-current-push-default-in-git-for-decentralized-workflow
- name: Set upstream for local branch push
  shell: "git config --global push.default current"
