---

- name: Execute OSX hombrew installation for vim
  import_tasks: osx-vim-install.yaml
  when: ansible_os_family == 'Darwin'

- name: Execute Linux package installation for vim
  import_tasks: linux-vim-install.yaml
  when: ansible_os_family == 'RedHat' or
    ansible_os_family == 'Debian'

- name: Install vim plugin manager (using CURL)
  shell: 'curl -fLo ~/.vim/autoload/plug.vim --create-dirs \
    https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim'

- name: Copy vim config
  copy:
    src: "{{ role_path }}/files/"
    dest: "~"
    force: yes

- name: Install vim-plug plugins
  shell: 'vim -E -s -c "source ~/.vimrc" -c PlugInstall -c PlugClean -c q -c q +qall'
