---

- name: homebrew cask install beyond-compare packages
  homebrew:
    name: "{{ item.name | default(item) }}"
    install_options: "{{ item.install_options | default(omit) }}"
    state: present
  loop:
    - beyond-compare

# https://www.scootersoftware.com/v4help/index.html?where_settings_are_stored.html
- name: Install beyond-compare settings
  copy:
    src: "{{ role_path }}/files/"
    dest: "~/Library/Application Support/Beyond Compare/"
    force: yes
