---

- name: Check if beyond-compare package is already installed
  shell: brew list --cask | grep beyond-compare
  register: homebrew_bc_installed
  failed_when: homebrew_bc_installed.rc > 1

- name: homebrew cask install beyond-compare packages
  homebrew:
    name: "{{ item.name | default(item) }}"
    install_options: "{{ item.install_options | default(omit) }}"
    state: present
  loop:
    - beyond-compare
  when: '"beyond-compare" not in homebrew_bc_installed.stdout'

# https://www.scootersoftware.com/v4help/index.html?where_settings_are_stored.html
- name: Install beyond-compare settings
  copy:
    src: "{{ role_path }}/files/"
    dest: "~/Library/Application Support/Beyond Compare/"
    force: yes
