---

- name: hombrew cask list packages
  command: brew list --cask
  register: brew_cask_list

- name: homebrew cask install sublime-text packages
  homebrew:
    name: "{{ item.name | default(item) }}"
    install_options: "{{ item.install_options | default(omit) }}"
    state: present
  loop:
    - sublime-text
  when: "item.name | default(item) not in brew_cask_list.stdout"

- name: Ensure sublime-text settings directories exist
  file:
    path: "{{ item }}"
    state: directory
  loop:
    - ~/Library/Application Support/Sublime Text 3/Installed Packages
    - ~/Library/Application Support/Sublime Text 3/Packages/User
